const settings = {
    MONGO_URI: null,
    MONG_DB: 'fiona',

    SUBS: [
        "Amateur",
        "AssOnTheGlass",
        "BDSM",
        "Bikinis",
        "BoobBounce",
        "Boobies",
        "Boobs",
        "Booty",
        "Bottomless",
        "Brazzers",
        "CheekyBottoms",
        "Cleavage",
        "Curls",
        "FireCrotch",
        "FreckledGirls",
        "GWCumSluts",
        "GWNerdy",
        "Ginger",
        "GirlsInLeggings",
        "GirlsInSchoolUniforms",
        "GirlsInYogaPants",
        "GoneMild",
        "GoneWild",
        "HighResNSFW",
        "HomemadeXXX",
        "Lingerie",
        "NSFW",
        "NSFWCosplay",
        "NSFWOutfits",
        "NSFWVideos",
        "NSFW_GIF",
        "NSFW_GIFS",
        "NSFW_HTML5",
        "NoPanties",
        "Nsfw_Amateurs",
        "OnOff",
        "OriginalBabes",
        "Pajamas",
        "PantyFetish",
        "PassionX",
        "PiercedNSFW",
        "PiercedTits",
        "Pokies",
        "PornVids",
        "RandomSexiness",
        "RealGirls",
        "RealityKings",
        "RedheadedGoddesses",
        "SFWRedheads",
        "SFWRedheads",
        "SeeThru",
        "SexyFrex",
        "SexyGirlsInBoots",
        "Stockings",
        "TheUnderBoob",
        "TheUnderBun",
        "TrueAmateurs",
        "UnderwearGW",
        "Undies",
        "Upskirt",
        "WorkGoneWild",
        "booty_gifs",
        "iWantToFuckHer",
        "palegirls",
        "redheads",
        "tightdresses"
      ],
};

module.exports = Object.keys(settings).reduce((a, key) => {
    a[key] = process.env[key] || settings[key];
    return a;
}, {});
